### PR TITLE
Add Error - middleware - Route and controller for Post models

### PR DESCRIPTION
**Pull request by tianahR**
Add managing errors, add middleware, fix Group Schema
Add createPost and createCategory
Add Get all posts - Add Get posts created by same author
Add deletePost and updatePost
Add pagination/filter for posts retrieved

### CODE REVIEW

**Review by vitaliipp — CHANGES_REQUESTED** [review]
Good job! 
If the functionality has not already been tested, please test it using Postman and include this fact in the description. 
Please ensure that the 'create post category' functionality is included in the MVP project. It seems that the middleware in src/middlewares/authentication.js has already been created by Mohammed in the file src/middlewares/verifyToken.js

**Comment by tianahR** [comment]
I made the change requested, except for the Category as we are not sure yet if it will be included in the MVP project or not.

Please see below screenshots of the test in Postman 

CREATE POST 

Create Post

GET ALL POSTS 

Get all posts

GET POSTS CREATED BY AN AUTHOR

Get all posts created by author

DELETE POST BY ID
Delete Post by ID

UPDATE POST BY ID

Update Post by ID

CREATE CATEGORY

Create Category

**Review by vitaliipp — APPROVED** [review]

**Review by mojahmed — APPROVED** [review]
good 😊

**Review by butolinka — APPROVED** [review]
looks good

**Pull request merged**
