### PR TITLE
Update user profile

### PR DESCRIPTION
**Pull request by mojahmed**

### CODE REVIEW

**Review by tianahR — COMMENTED** [review]
It looks good  to me.

**Review by butolinka — APPROVED** [review]
looks good for me

**Review by vitaliipp — CHANGES_REQUESTED** [review]
Good job!
Please provide a description of the changes made. 
If the functionality has not already been tested, please test it using Postman and include this fact in the description. 
I recommend removing the 'change password' functionality from the 'update user profile' controller and creating a separate controller specifically for changing passwords

**Comment by mojahmed** [comment]
> Good job! Please provide a description of the changes made. If the functionality has not already been tested, please test it using Postman and include this fact in the description. I recommend removing the 'change password' functionality from the 'update user profile' controller and creating a separate controller specifically for changing passwords

Thank you for your feedback! I have made the changes you requested

**Comment by mojahmed** [comment]
- (first comment on the branch)= `updateUserProfileCtrl` function is implemented to allow users to update their **first name** and **last name** and the bio ,

- (first comment on the branch) =**Deleted empty files**

-(first comment on the branch)=  The route for this functionality is `PUT /api/auth/profile/:id`, where `:id` is the user ID.

-(second comment on the branch) =Based on the Vitalii Popovych feedback, I **refactored the "update password" functionality** from the `updateUserProfileCtrl` to a **separate controller** (`changePasswordCtrl`) to ensure a cleaner, more modular design.

-(second comment on the branch) A new route (`PUT /api/users/change-password/:id`) has been created for changing a user's password independently from updating other profile information.

- ##all the user profile update and password change and sign up - login functionalities were tested using **Postman**, and all tests passed successfully.

**Review by tianahR — COMMENTED** [review]
Good

**Review by vitaliipp — APPROVED** [review]
Great job!

**Pull request merged**
